{% set name = "custodian" %}
{% set version = "2019.9.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba1ebb17c524fb502f42382d363d2f20ea09eef63ccabea810a4c31349bd7d89

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - cstdn = custodian.cli.cstdn:main
    - run_vasp = custodian.cli.run_vasp:main
    - run_nwchem = custodian.cli.run_nwchem:main
    - converge_kpoints = custodian.cli.converge_kpoints:main
    - converge_geometry = custodian.cli.converge_geometry:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pip
    - sentry-sdk
    - ruamel.yaml >=0.15.6
    - monty >=0.9.0
    - six

test:
  imports:
    - custodian
  commands:
    - pip check

about:
  home: https://materialsproject.github.io/custodian
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A simple, robust and flexible just-in-time job management framework in Python.'

  description: |
    Custodian is a simple, robust and flexible just-in-time (JIT) job 
    management framework written in Python. Using custodian, you can 
    create wrappers that perform error checking, job management and 
    error recovery. It has a simple plugin framework that allows you 
    to develop specific job management workflows for different 
    applications.
  doc_url: https://materialsproject.github.io/custodian
  dev_url: https://github.com/materialsproject/custodian

extra:
  recipe-maintainers:
    - shyuep
    - mkhorton
    - jan-janssen
