{% set name = "custodian" %}
{% set version = "2025.5.12" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/materialsproject/custodian/archive/v{{ version }}.tar.gz
  sha256: 8abcef3bb4bb92fcaf90ae3c8a24600ee295cb9a1312cf57e9f5ed8325a5250c

build:
  entry_points:
    - cstdn = custodian.cli.cstdn:main
    - run_vasp = custodian.cli.run_vasp:main
    - run_nwchem = custodian.cli.run_nwchem:main
    - converge_kpoints = custodian.cli.converge_kpoints:main
    - converge_geometry = custodian.cli.converge_geometry:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - monty >=2.0.6
    - ruamel.yaml >=0.15.6
    - sentry-sdk >=0.8.0
    - psutil

test:
  imports:
    - custodian
  commands:
    - pip check
    - cstdn --help
    - run_vasp --help
    - run_nwchem --help
    - converge_kpoints --help
    # - converge_geometry --help
  requires:
    - pip
    - pymatgen
    - python {{ python_min }}

about:
  home: https://github.com/materialsproject/custodian
  summary: A simple JIT job management framework in Python.
  doc_url: https://pythonhosted.org/custodian/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shyuep
    - mkhorton
    - jan-janssen
