{% set name = "custodian" %}
{% set version = "2024.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/custodian-{{ version }}.tar.gz
  sha256: e57ff300d21ff63a08b63be6b8e1b1d5175178a2f77ac8666ffdf63c2d83808e

build:
  entry_points:
    - cstdn = custodian.cli.cstdn:main
    - run_vasp = custodian.cli.run_vasp:main
    - run_nwchem = custodian.cli.run_nwchem:main
    - converge_kpoints = custodian.cli.converge_kpoints:main
    - converge_geometry = custodian.cli.converge_geometry:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - monty >=2.0.6
    - ruamel.yaml >=0.15.6
    - sentry-sdk >=0.8.0
    - psutil

test:
  imports:
    - custodian
  commands:
    - pip check
    - cstdn --help
    - run_vasp --help
    - run_nwchem --help
    - converge_kpoints --help
    # - converge_geometry --help
  requires:
    - pip
    - pymatgen

about:
  home: https://github.com/materialsproject/custodian
  summary: A simple JIT job management framework in Python.
  doc_url: https://pythonhosted.org/custodian/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shyuep
    - mkhorton
    - jan-janssen
