travis:
  secure:
    BINSTAR_TOKEN: BmR3FdXAJbsRwBgetZ2BQFuUdopArAu2ECGCjuWkYbnP4UPTwP/vkCar0ywmR5uTM53xNnSdi+DuXTJarPqv06aa7buwJaJrLxut0uArWABPkA+PmgzTCIgawJyi/99AZgKzKkFbujezOCm5AgQKJCIcqGK6ODIwnxZ+oYjpaCwAG5sA7NipiV11G6sIjvZhuk3S4SwS+2ewOkemaVH53Hm8bHyJ2MRFuA/7SqRyoZWYO6w7397ubDEcdhDkq5zjiJurJsJc1Okc/E9akawwSjCYwMPKHh3DuAcesQLGpsx1HkY+PLw6vSjARfUTFVFHQJQfPEefrcHYuZhVjInMpxsuTM3OwIm8zvgaOsc4Wyq1M3BUYYHFdSGu6EQoCjyoKwXS9WUHC8+dY/zCPeMMOIOU4NxBfVAEPElBTq48AqaOnah3tcCRl6c6MdVKRXvQJdyoemjcM0AJdsDFw6q5ieEbPR0RCN4ePutN18434CdWXEcEm0qEEFvZFVtAvqm20d/FPc9zGQDc8S4oKC0XVcCw+6TRro4L6SZ0FvzUzNRyE5pZBJSgYe+kAjqqc88ffk0yZEzDOMAZdxJxu1a1egDFxwDS/Ik7+K2M9zEml1BPMmWBNjl9OmVldzPUIWbcT5enxZY5DpW2bVQvrs2pniTJPxP/Cth3eQAoG0cyKwI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
